SELECT * FROM TBL_MEMBER;
SELECT * FROM TBL_BOOK;

-- 조건 조회 (VIP 회원만)
SELECT * FROM TBL_MEMBER
WHERE MEMBER_GRADE LIKE 'VIP';

-- VIP 회원의 평균 나이
SELECT AVG(MEMBER_AGE) 
FROM TBL_MEMBER
WHERE MEMBER_GRADE LIKE 'VIP';

-- 회원 등급 별 평균 나이
SELECT MEMBER_GRADE ,AVG(MEMBER_AGE)
FROM TBL_MEMBER
GROUP BY MEMBER_GRADE;

-- 나이 30살 이상 남성 회원
SELECT * FROM TBL_MEMBER
WHERE MEMBER_GENDER LIKE '%남성%';


SELECT * FROM TBL_MEMBER
WHERE 
	MEMBER_GENDER LIKE '%남성%' AND 
	MEMBER_AGE >= 30;

-- IT 도서 가격 순 정렬
SELECT * FROM TBL_BOOK
ORDER BY BOOK_PRICE DESC;


-- ✅ UPDATE 연습
-- 특정 회원 등급 변경
UPDATE TBL_MEMBER SET MEMBER_GRADE = 'VIP' WHERE MEMBER_ID = 1;

UPDATE TBL_BOOK SET BOOK_STOCK = BOOK_STOCK - 1 WHERE BOOK_ID = 1;

DELETE FROM TBL_MEMBER WHERE MEMBER_ID = 35;

ALTER TABLE TBL_MEMBER ADD ADDRESS VARCHAR2(255);
ALTER TABLE TBL_MEMBER DROP COLUMN ADDRESS;

ALTER TABLE TBL_MEMBER ADD MEMBER_CARD_NUM VARCHAR2(25);

ALTER TABLE TBL_MEMBER ADD CONSTRAINT UK_MEMBER_CARD_NUM UNIQUE(MEMBER_CARD_NUM);
ALTER TABLE TBL_MEMBER DROP COLUMN MEMBER_CARD_NUM;

SELECT * FROM TBL_MEMBER;

CREATE SEQUENCE SEQ_RENTAL;
CREATE TABLE TBL_RENTAL(
	ID NUMBER CONSTRAINT PK_RENTAL PRIMARY KEY,
	RENTAL_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	RENTAL_DEADLINE TIMESTAMP DEFAULT CURRENT_TIMESTAMP + 7
);

ALTER TABLE TBL_RENTAL ADD MEMBER_ID NUMBER;
ALTER TABLE TBL_RENTAL ADD BOOK_ID NUMBER;
ALTER TABLE TBL_RENTAL ADD CONSTRAINT FK_RENTAL_MEMBER FOREIGN KEY(MEMBER_ID) REFERENCES TBL_MEMBER(MEMBER_ID);
ALTER TABLE TBL_RENTAL ADD CONSTRAINT FK_RENTAL_BOOK FOREIGN KEY(BOOK_ID) REFERENCES TBL_BOOK(BOOK_ID);

ALTER TABLE TBL_RENTAL MODIFY MEMBER_ID NOT NULL;
ALTER TABLE TBL_RENTAL MODIFY BOOK_ID NOT NULL;




