CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(50) NOT NULL,
	MEMBER_EMAIL VARCHAR2(100) UNIQUE,
	MEMBER_AGE NUMBER,
	MEMBER_REG_DATE DATE DEFAULT SYSDATE
);

--테이블명: PRODUCT
--컬럼:
--
--ID           : 숫자, PK (시퀀스 사용)
--PRODUCT_NAME : 문자 최대 100자, NOT NULL
--PRODUCT_PRICE: 숫자, NOT NULL
--STOCK        : 숫자, DEFAULT 0
CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(100) NOT NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 999
);


--**Q4.** 주문 테이블을 작성하세요. (FK 포함)
--```
--테이블명: ORDER_LIST
--컬럼:
--  - ID         : 숫자, PK (시퀀스 사용)
--  - MEMBER_ID  : 숫자, FK → TBL_MEMBER(ID)
--  - PRODUCT_ID : 숫자, FK → TBL_PRODUCT(ID)
--  - ORDER_QTY  : 숫자, NOT NULL
--  - ORDER_DATE : 날짜, DEFAULT SYSDATE
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_QTY NUMBER NOT NULL,
	ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER NOT NULL,
	PRODUCT_ID NUMBER NOT NULL,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);


--**Q5.** `TBL_MEMBER` 테이블에 전화번호 컬럼을 추가하세요.
--컬럼명: MEMBER_PHONE / 타입: VARCHAR2(20)
ALTER TABLE TBL_MEMBER ADD MEMBER_PHONE VARCHAR2(20);


SELECT * FROM TBL_MEMBER;


--Q6. MEMBER_PHONE 컬럼의 타입을 VARCHAR2(30)으로 변경하세요.
ALTER TABLE TBL_MEMBER MODIFY MEMBER_PHONE VARCHAR2(30);


--Q7. MEMBER_PHONE 컬럼명을 MEMBER_TEL로 변경하세요.
ALTER TABLE TBL_MEMBER RENAME COLUMN MEMBER_PHONE TO MEMBER_TEL;



--Q8. MEMBER_TEL 컬럼을 삭제하세요.
ALTER TABLE TBL_MEMBER DROP COLUMN MEMBER_TEL;


--Q10. FK 관계가 있는 상황에서 TBL_MEMBER를 삭제하려면 어떤 순서로 해야 하나요?

DROP TABLE TBL_ORDER;
DROP TABLE TBL_MEMBER;
DROP TABLE TBL_PRODUCT;


-- 고객 테이블
-- ID, 고객명, 등급
CREATE SEQUENCE SEQ_CUSTOMER;
CREATE TABLE TBL_CUSTOMER(
	ID NUMBER CONSTRAINT PK_CUSTOMER PRIMARY KEY,
	CUSTOMER_NAME VARCHAR2(255) NOT NULL,
	CUSTOMER_GRADE CHAR(10) DEFAULT '일반',
	CUSTOMER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 상품 테이블
-- ID, 상품명, 가격
CREATE SEQUENCE SEQ_ITEM;
CREATE TABLE TBL_ITEM(
	ID NUMBER CONSTRAINT PK_ITEM PRIMARY KEY,
	ITEM_NAME VARCHAR2(255) NOT NULL,
	ITEM_PRICE NUMBER NOT NULL,
	ITEM_STOCK NUMBER DEFAULT 999
);




-- 주문내역 테이블
-- ID, 주문번호, 상품코드, 수량
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_CODE CHAR(20) UNIQUE NOT NULL,
	ORDER_QTY NUMBER DEFAULT 1,
	CUSTOMER_ID NUMBER NOT NULL,
	ITEM_ID NUMBER NOT NULL,
	CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY(CUSTOMER_ID)
	REFERENCES TBL_CUSTOMER(ID),
	CONSTRAINT FK_ORDER_ITEM FOREIGN KEY(ITEM_ID)
	REFERENCES TBL_ITEM(ID)
);



