CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255) NOT NULL,
	USER_AGE NUMBER NOT NULL,
	USER_GENDER CHAR(3) NOT NULL
);

ALTER TABLE TBL_USER MODIFY USER_GENDER CHAR(8);

INSERT INTO TBL_USER VALUES(SEQ_USER.NEXTVAL, '홍길동', 20, '남성');
INSERT INTO TBL_USER VALUES(SEQ_USER.NEXTVAL, '이규학', 25, '남성');
INSERT INTO TBL_USER VALUES(SEQ_USER.NEXTVAL, '황미야', 33, '여성');
INSERT INTO TBL_USER VALUES(SEQ_USER.NEXTVAL, '장보고', 22, '남자');

ALTER TABLE TBL_USER ADD USER_ADDRESS VARCHAR2(255);

UPDATE TBL_USER SET USER_ADDRESS = '서울시 강남구' WHERE ID = 2;
UPDATE TBL_USER SET USER_ADDRESS = '서울시 강서구' WHERE ID = 3;
UPDATE TBL_USER SET USER_ADDRESS = '서울시 마포구' WHERE ID = 4;
UPDATE TBL_USER SET USER_ADDRESS = '서울시 서초구' WHERE ID = 5;

DELETE FROM TBL_USER
WHERE ID = 5;

ALTER TABLE TBL_USER RENAME COLUMN USER_NAME TO USER_FULL_NAME;
ALTER TABLE TBL_USER RENAME TO TBL_CUSTOMER;

ALTER TABLE TBL_CUSTOMER DROP COLUMN USER_ADDRESS;

SELECT * FROM TBL_CUSTOMER;