
-- 사전지식 1
-- 알리아스 붙이면 알리아스 로만 접근 가능
SELECT TBP.PRODUCT_NAME 
FROM TBL_PRODUCT TBP;

-- 가상 연산자
SELECT 5 +3 FROM DUAL;

-- 부호 SIGN
-- 음수 냐 양수 냐 판단하는거 EX) 흑자 적자 판단
SELECT SIGN(100) FROM DUAL; 
SELECT SIGN(-100) FROM DUAL; 

-- 논리 연산자
-- !=, <>
SELECT * 
FROM TBL_PRODUCT
WHERE PRODUCT_PRICE <> 25300;


-- 가격대가 10만원 부터 20만원 까지
-- BETWEEN 사이값 범위 줄 수 있다.
SELECT * FROM TBL_PRODUCT
WHERE PRODUCT_PRICE BETWEEN 100000 AND 200000;


-- 문자열 연산자
-- CONCAT() 문자열 연결
SELECT CONCAT('HELLO', 'WORLD') FROM DUAL;

-- SUBSTRING() 문자열 추출 (인덱스는 1 부터 시작)
SELECT SUBSTR('HELLO WORLD', 7, 5) FROM DUAL;


-- 중복 연산자
CREATE SEQUENCE SEQ_TEST;
CREATE TABLE TBL_TEST(
	ID NUMBER CONSTRAINT PK_TEST PRIMARY KEY,
	TEST_NAME VARCHAR2(255),
	TEST_PRICE NUMBER
);

INSERT INTO TBL_TEST
VALUES(SEQ_TEST.NEXTVAL, '지우개', 20000);
INSERT INTO TBL_TEST
VALUES(SEQ_TEST.NEXTVAL, '지우개', 20000);
INSERT INTO TBL_TEST
VALUES(SEQ_TEST.NEXTVAL, '지우개', 20000);
INSERT INTO TBL_TEST
VALUES(SEQ_TEST.NEXTVAL, '지우개', 30000);
INSERT INTO TBL_TEST
VALUES(SEQ_TEST.NEXTVAL, '지우개', 15000);
INSERT INTO TBL_TEST
VALUES(SEQ_TEST.NEXTVAL, '키보드', 10000);
INSERT INTO TBL_TEST
VALUES(SEQ_TEST.NEXTVAL, '모니터', 20000);



CREATE SEQUENCE SEQ_TEST_ORDER;
CREATE TABLE TBL_TEST_ORDER(
	ID NUMBER CONSTRAINT PK_TEST_ORDER PRIMARY KEY,
	TEST_ORDER_NAME VARCHAR2(255),
	TEST_ID NUMBER,
	CONSTRAINT FK_TEST_ORDER_TEST FOREIGN KEY(TEST_ID)
	REFERENCES TBL_TEST(ID)
);


INSERT INTO TBL_TEST_ORDER
VALUES (SEQ_TEST_ORDER.NEXTVAL, '문 앞', 1);
INSERT INTO TBL_TEST_ORDER
VALUES (SEQ_TEST_ORDER.NEXTVAL, '직접 수령', 2);
INSERT INTO TBL_TEST_ORDER
VALUES (SEQ_TEST_ORDER.NEXTVAL, '직접 수령', 2);


SELECT TEST_NAME FROM TBL_TEST
UNION
SELECT TEST_ORDER_NAME FROM TBL_TEST_ORDER;


SELECT TEST_NAME FROM TBL_TEST
UNION ALL
SELECT TEST_ORDER_NAME FROM TBL_TEST_ORDER;


SELECT TEST_NAME FROM TBL_TEST
MINUS
SELECT TEST_ORDER_NAME FROM TBL_TEST_ORDER;


SELECT * FROM TBL_TEST
UNION ALL
SELECT * FROM TBL_TEST_ORDER;




SELECT UPPER('abcdEFGH') FROM DUAL;
SELECT LOWER('abcdEFGH') FROM DUAL;
SELECT TRIM('abcd    EFGH') FROM DUAL;
SELECT TRIM('    abcd    EFGH   ') FROM DUAL;

-- 문자열 내 모든 데이터 변경
SELECT REPLACE('APPLE', 'P', 'E') FROM DUAL;

SELECT INSTR('APPLE', 'L') FROM DUAL;


-- 날짜 및 시간함수
SELECT SYSDATE FROM DUAL;
SELECT CURRENT_DATE FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL;

SELECT MONTHS_BETWEEN(SYSDATE, ADD_MONTHS(SYSDATE, 2)) FROM DUAL;

-- 일 차이
SELECT (SYSDATE - TO_DATE('2026-01-01-12:25:00', 'YYYY-MM-DD HH24:MI:SS')) FROM DUAL;

-- 시 차이
SELECT (SYSDATE - TO_DATE('2026-01-01-12:25:00', 'YYYY-MM-DD HH24:MI:SS')) * 24  FROM DUAL;

-- 분 차이
SELECT (SYSDATE - TO_DATE('2026-01-01-12:25:00', 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60 FROM DUAL;

-- 초 차이
SELECT (SYSDATE - TO_DATE('2026-01-01-12:25:00', 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60 * 60 FROM DUAL;


-- 1 일	
-- 2 월
-- 3 화
-- 4 수
-- 5 목
-- 6 금
-- 7 토
SELECT NEXT_DAY(SYSDATE, 7) FROM DUAL;
SELECT NEXT_DAY(base_date, 7) AS 다음주_토요일
FROM (
    SELECT NEXT_DAY(SYSDATE, 7) AS base_date
    FROM DUAL
);


-- TO CHAR 문자
SELECT TO_CHAR ('2026-01-01 17:15:10' , 'YYYY-MM-DD HH24-MI-SS') FROM DUAL;

-- 이건 DATE 를 바꾼걸 다시 형식에 맞게 CHAR 로 바꾸기 위해서 뒤에 어떤 식으로 할 지 양식을 넣어야 합니다.
SELECT TO_CHAR(
    TO_DATE('2026-01-01 17:15:10', 'YYYY-MM-DD HH24:MI:SS'),
    'HH24'
) FROM DUAL;
SELECT TO_CHAR(
    TO_DATE('2026-01-01 17:15:10', 'YYYY-MM-DD HH24:MI:SS'),
    'MI'
) FROM DUAL;
SELECT TO_CHAR(
    TO_DATE('2026-01-01 17:15:10', 'YYYY-MM-DD HH24:MI:SS'),
    'SS'
) FROM DUAL;


-- 숫자형 함수
SELECT ABS(-100) FROM DUAL;
SELECT CEIL(3.14) FROM DUAL;
SELECT FLOOR(3.14) FROM DUAL;
SELECT MOD(5, 2) FROM DUAL;
SELECT ROUND(123.456, 2) FROM DUAL;
SELECT POWER(10, 3) FROM DUAL;

SELECT TO_NUMBER('123') + 4 FROM DUAL;
SELECT TO_TIMESTAMP('2026-03-18', 'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL;
SELECT TO_DATE('2025-12-26', 'YYYY-MM-DD') FROM DUAL;

-- CAST()
SELECT CAST(10 AS VARCHAR2(255)) FROM DUAL;


-- NULL 대체
SELECT * 
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;


SELECT TBT.*, TBO.*, NVL(TBO.TEST_ORDER_NAME, '없음')
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;


-- NVL2: 삼함
SELECT TBT.*, TBO.*, NVL2(TBO.TEST_ORDER_NAME, '있음', '없음')
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;


-- COALESCE 앞에서 부터 돌면서 값이 있는걸 리턴 하는거
SELECT TBT.*, TBO.*, COALESCE(TBO.TEST_ORDER_NAME, TBT.TEST_NAME, TBT.TEST_NAME)
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;


--NULLIF
-- 두 값이 같으면 NULL, 다르면 첫 값 반환 , 넘버만 가능
SELECT TBT.*, TBO.*, NULLIF(TBT.ID, TBO.ID)
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;


-- CASE문
-- 컬럼 명을 변수처럼 써서 간소화 여부 차이
SELECT 
	TBT.*, 
	TBO.*,
	CASE TBO.TEST_ORDER_NAME
		WHEN '문 앞' THEN '문 앞에 놔둬주세요'
		WHEN '직접 수령' THEN '직접 받겠습니다.'
		ELSE '안전한 배송 감사합니다.'
	END
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;
  

SELECT 
	TBT.*, 
	TBO.*,
	CASE 
		WHEN TBO.TEST_ORDER_NAME IS NOT NULL THEN '문 앞에 놔둬주세요'
		WHEN TBO.TEST_ORDER_NAME IS NULL THEN '안전한 배송 감사합니다.'
	END
FROM TBL_TEST TBT
LEFT JOIN TBL_TEST_ORDER TBO 
ON TBT.ID = TBO.TEST_ID;


-- 윈도우 함수 (데이터의 그룹화) [집계 함수]
-- 매 기수마다 나오는 함수
SELECT
	RANK() OVER(ORDER BY TEST_PRICE DESC) "가격 순위",
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;

-- 순위 매길 때 공동순위 처리 하고 건너뛰지 아니하는것
SELECT
	DENSE_RANK() OVER(ORDER BY TEST_PRICE DESC) "가격 순위",
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;

-- 중복 없이 순위 처리하는거
SELECT
	ROW_NUMBER() OVER(ORDER BY TEST_PRICE DESC) "가격 순위",
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;


-- 이번에는 파티션 나누기
-- 그룹별로 순위 매기는게 가능한 개념
SELECT
	ROW_NUMBER() OVER(PARTITION BY TEST_NAME ORDER BY TEST_PRICE DESC),
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;

SELECT
	DENSE_RANK() OVER(PARTITION BY TEST_NAME ORDER BY TEST_PRICE DESC),
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;

SELECT
	RANK() OVER(PARTITION BY TEST_NAME ORDER BY TEST_PRICE DESC),
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;


-- SUM 관련도 가능
-- 각 그룹 별 집계 결과를 나타내줌
SELECT
--	ROW_NUMBER() OVER(PARTITION BY TEST_PRICE ORDER BY TEST_PRICE DESC),
	SUM(TEST_PRICE) OVER(PARTITION BY TEST_NAME),
	TEST_NAME,
	TEST_PRICE
FROM TBL_TEST;

-- 월급인상률 부분에 주로 쓰임
SELECT
	TEST_NAME,
	TEST_PRICE,
	LEAD(TEST_PRICE) OVER(ORDER BY TEST_PRICE)
FROM TBL_TEST;

SELECT
	TEST_NAME,
	TEST_PRICE,
	LAG(TEST_PRICE) OVER(ORDER BY TEST_PRICE)
FROM TBL_TEST;

SELECT
	TEST_NAME,
	TEST_PRICE,
	FIRST_VALUE(TEST_PRICE) OVER(ORDER BY TEST_PRICE)
FROM TBL_TEST;

SELECT
	TEST_NAME,
	TEST_PRICE,
	LAST_VALUE(TEST_PRICE) OVER(ORDER BY TEST_PRICE DESC)
FROM TBL_TEST;


SELECT
	TEST_NAME,
	TEST_PRICE,
	NTH_VALUE(TEST_PRICE, 1) OVER(ORDER BY TEST_PRICE DESC)
FROM TBL_TEST;


SELECT * FROM TBL_TEST;
UPDATE TBL_TEST
SET TEST_PRICE = 30000
WHERE TEST_NAME = '키보드';

-- ROLLUP
SELECT 
	TEST_NAME,
	TEST_PRICE
--	SUM(TEST_PRICE) OVER(PARTITION BY TEST_NAME)
FROM TBL_TEST
GROUP BY ROLLUP(TEST_NAME, TEST_PRICE);










