--/*
--   요구사항
--   음료수 판매 업체입니다. 음료수마다 당첨번호가 있습니다. 
--   음료수의 당첨번호는 1개이고 당첨자의 정보를 알아야 상품을 배송할 수 있습니다.
--   당첨 번호마다 당첨 상품이 있고, 당첨 상품이 배송 중인지 배송 완료인지 구분해야 합니다.
--*/
--
---- 음료수
---- TBL_SOFT_DRINK
---- 이름, 가격, 재고, 재조일
--CREATE SEQUENCE SEQ_SOFT_DRINK;
--CREATE TABLE TBL_SOFT_DRINK(
--   ID NUMBER CONSTRAINT PK_SOFT_DRINK PRIMARY KEY,
--   SOFT_DRINK_NAME VARCHAR2(255) NOT NULL,
--   SOFT_DRINK_PRICE NUMBER DEFAULT 0,
--   SOFT_DRINK_STOCK NUMBER DEFAULT 999,
--   SOFT_DRINK_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
--
---- 상품
---- TBL_PRODUCT
---- 이름, 재고
--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--   PRODUCT_NAME VARCHAR2(255) NOT NULL,
--   PRODUCT_STOCK NUMBER DEFAULT 999
--);
--
---- 사용자
---- TBL_USER
---- 이름, 주소, 번호
--CREATE SEQUENCE SEQ_USER;
--CREATE TABLE TBL_USER(
--   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,   
--   USER_NAME VARCHAR2(255) NOT NULL,
--   USER_ADDRESS VARCHAR2(255) NOT NULL,
--   USER_PHONE VARCHAR2(255) NOT NULL
--);
--
---- 주문
---- TBL_ORDER
---- 주문날짜, USER_ID, SOFT_DRINK_ID
--CREATE SEQUENCE SEQ_ORDER;
--CREATE TABLE TBL_ORDER(
--   ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
--   ORDER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   USER_ID NUMBER,
--   SOFT_DRINK_ID NUMBER,
--   CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
--   REFERENCES TBL_USER(ID),
--   CONSTRAINT FK_ORDER_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
--   REFERENCES TBL_SOFT_DRINK(ID)
--);
--
---- 당첨(운)
---- TBL_LOTTERY
---- SOFT_DRINK_ID
--CREATE SEQUENCE SEQ_LOTTERY;
--CREATE TABLE TBL_LOTTERY(
--   ID NUMBER CONSTRAINT PK_LOTTERY PRIMARY KEY,
--   SOFT_DRINK_ID NUMBER,
--   CONSTRAINT FK_LOTTERY_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
--   REFERENCES TBL_SOFT_DRINK(ID)
--);
--
---- 추첨
---- TBL_CIRULATION
---- LOTTERY_ID, PRODUCT_ID
--CREATE SEQUENCE SEQ_CIRULATION;
--CREATE TABLE TBL_CIRULATION(
--   ID NUMBER CONSTRAINT PK_CIRULATION PRIMARY KEY,
--   LOTTERY_ID NUMBER,
--   PRODUCT_ID NUMBER,
--   CONSTRAINT FK_CIRULATION_LOTTERY FOREIGN KEY(LOTTERY_ID)
--   REFERENCES TBL_LOTTERY(ID),
--   CONSTRAINT FK_CIRULATION_PRODUCT FOREIGN KEY(PRODUCT_ID)
--   REFERENCES TBL_PRODUCT(ID)
--);
--
--
---- 배송
---- TBL_DELIVERY
---- PRODUCT_ID, USER_ID
--CREATE SEQUENCE SEQ_DELIVERY;
--CREATE TABLE TBL_DELIVERY(
--   ID NUMBER CONSTRAINT PK_DELIVERY PRIMARY KEY,
--   PRODUCT_ID NUMBER,
--   USER_ID NUMBER,
--   CONSTRAINT FK_DELIVERY_PRODUCT FOREIGN KEY(PRODUCT_ID)
--   REFERENCES TBL_PRODUCT(ID),
--   CONSTRAINT FK_DELIVERY_USER FOREIGN KEY(USER_ID)
--   REFERENCES TBL_USER(ID)
--);




/*
   요구사항
   음료수 판매 업체입니다. 음료수마다 당첨번호가 있습니다. 
   음료수의 당첨번호는 1개이고 당첨자의 정보를 알아야 상품을 배송할 수 있습니다.
   당첨 번호마다 당첨 상품이 있고, 당첨 상품이 배송 중인지 배송 완료인지 구분해야 합니다.
*/

-- 음료수
-- 이름, 가격, 당첨ID
-- 음료수 : 당첨번호 = 1 : 1
-- 하나의 당첨 번호는 하나의 음료수 에만 할당
--CREATE SEQUENCE SEQ_DRINK;
--CREATE TABLE TBL_DRINK(
--	DRINK_NAME VARCHAR2(255),
--	DRINK_PRICE NUMBER DEFAULT 0,
--	JACKPOT_ID NUMBER,
--	CONSTRAINT FK_DRINK_JACKPOT FOREIGN KEY(JACKPOT_ID)
--	REFERENCES TBL_JACKPOT(ID)
--);
--
--ALTER TABLE TBL_DRINK ADD CONSTRAINT UQ_DRINK_JACKPOT_ID UNIQUE(JACKPOT_ID);
--ALTER TABLE TBL_DRINK ADD ID NUMBER;
--ALTER TABLE TBL_DRINK ADD CONSTRAINT PK_DRINK PRIMARY KEY(ID);
--
-- 당첨번호 테이블
---- 당첨번호, 상품ID
---- 당첨번호 테이블 : 상품 테이블 = N : 1
---- 하나의 상품은 여러 당첨번호에 할당 가능 (당첨번호 구간)
--CREATE SEQUENCE SEQ_JACKPOT;
--CREATE TABLE TBL_JACKPOT(
--	ID NUMBER CONSTRAINT PK_JACKPOT PRIMARY KEY,
--	JACKPOT_CODE NUMBER UNIQUE NOT NULL,
--	GIFT_ID NUMBER,
--	CONSTRAINT FK_JACKPOT_GIFT FOREIGN KEY(GIFT_ID)
--	REFERENCES TBL_GIFT(ID)
--);
--
--
---- 당첨 상품 정보
---- 상품 명, 재고수량, 원산지
---- 당첨이 안된거를 가정 하는건 꽝 이라는 상품
--CREATE SEQUENCE SEQ_GIFT;
--CREATE TABLE TBL_GIFT(
--	ID NUMBER CONSTRAINT PK_GIFT PRIMARY KEY,
--	GIFT_NAME VARCHAR2(255) NOT NULL,
--	GIFT_STOCK NUMBER DEFAULT 999,
--	GIFT_LOCATION VARCHAR2(255) NOT NULL
--);
--
---- 유저 정보 테이블
---- 이름, 주소, 연락처
--CREATE SEQUENCE SEQ_USER;
--CREATE TABLE TBL_USER(
--	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
--	USER_NAME VARCHAR2(255) NOT NULL,
--	USER_ADDRESS VARCHAR2(255) NOT NULL,
--	USER_PHONE VARCHAR2(255) NOT NULL
--);
--
---- 당첨 테이블 TBL_SELECTED 선택받은 자
---- 유저는 여러개의 당첨 번호를 가질 수 있음 (많은 음료수를 구매 한 결과 당첨이 2개 이상 나올수도 있음)
---- 그러나 각각의 당첨 번호는 고유해야 함 (하나의 당첨 번호에 2명의 유저에게 당첨으로 할당 불가능)
---- 당첨ID, 송장번호, 배송 상태
---- 일단 송장번호는 당첨이 되는 순간 회사 송장 프로그램에 의해서 자동 생성 된다고 가정 (3PL 이용 가정)
---- 송장번호는 번호로만 존재 가능하며, 기사님이 수거 해서 스캔 찍는 순간 부터 배송 현황이 누적됨
--CREATE SEQUENCE SEQ_SELECTED;
--CREATE TABLE TBL_SELECTED(
--	ID NUMBER CONSTRAINT PK_SELECTED PRIMARY KEY,
--	SELECTED_DELIVERY_LABEL NUMBER NOT NULL,
--	USER_ID NUMBER,
--	JACKPOT_ID NUMBER,
--	CONSTRAINT FK_SELECTED_USER FOREIGN KEY(USER_ID)
--	REFERENCES TBL_USER(ID),
--	CONSTRAINT FK_SELECTED_JACKPOT FOREIGN KEY(JACKPOT_ID)
--	REFERENCES TBL_JACKPOT(ID)
--);
--
--
---- 사용자가 음료수를 주문하는 테이블도 존재
---- 주문날짜
--
--
---- 배송현황 테이블
---- 상태가 변경 된 시점 별로의 현재 상태, 위치, 등을 나타내 줘야 함
---- 하나의 배송건은 누적된 여러개의 배송 상태를 가짐 (집하, 간선상차, 간선하차, 대리점 도착, 배송중, 배송완료)
---- ID, FK SELECTED, 현재 위치, 도착 시간, 기사님 성함, 기사님 연락처, 상태 
--CREATE SEQUENCE SEQ_DELIVERY_STATE;
--CREATE TABLE TBL_DELIVERY_STATE(
--	ID NUMBER CONSTRAINT PK_DELIVERY_STATE PRIMARY KEY,
--	DELIVERY_STATE_LOCATION VARCHAR2(255) NOT NULL,
--	DELIVERY_STATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--	DELIVERY_STATE_DRIVER_NAME VARCHAR2(255),
--	DELIVERY_STATE_DRIVER_PHONE VARCHAR2(255),
--	SELECTED_ID NUMBER,
--	CONSTRAINT FK_DELIVERY_STATE_SELECTED FOREIGN KEY(SELECTED_ID)
--	REFERENCES TBL_SELECTED(ID)
--);
--
---- 배송 현황 테이블에 NOW_STATE 라는 열 추가하기
--ALTER TABLE TBL_DELIVERY_STATE ADD DELIVERY_STATE_NOW_STATE CHAR(10);
--ALTER TABLE TBL_DELIVERY_STATE MODIFY DELIVERY_STATE_NOW_STATE NOT NULL;
--
---- SELECTD 에서 송장 번호는 유효 해야함
--
--
--SELECT * FROM TBL_DELIVERY_STATE;
--
----상품정보 테이블
---- 상품 이름
--
--
--
--/*
--   요구사항
--   이커머스 창업 준비중입니다. 기업과 사용자 간 거래를 위해 기업의 정보와 사용자 정보가 필요합니다.
--   기업의 정보는 기업 이름, 주소, 대표번호가 있고
--   사용자 정보는 이름, 주소, 전화번호가 있습니다. 결제 시 사용자 정보와 기업의 정보, 결제한 카드의 정보 모두 필요하며,
--   상품의 정보도 필요합니다. 상품의 정보는 이름, 가격, 재고입니다.
--   사용자는 등록한 카드의 정보를 저장할 수 있으며, 카드의 정보는 카드번호, 카드사, 회원 정보가 필요합니다.
--*/
--
---- 기업 (판매하는 몰) 정보 TBL_COMPANY
---- 기업 이름, 주소, 대표번호
--CREATE SEQUENCE SEQ_COMPANY;
--CREATE TABLE TBL_COMPANY(
--	ID NUMBER CONSTRAINT PK_COMPANY PRIMARY KEY,
--	COMPANY_NAME VARCHAR2(255) NOT NULL UNIQUE,
--	COMPANY_ADDRESS VARCHAR2(255) NOT NULL,
--	COMPANY_PHONE VARCHAR2(255) NOT NULL,
--	COMPANY_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
--
---- 상품 정보(기업이 판매를 하는 FK) TBL_ITEM
---- 이름, 가격, 재고
--CREATE SEQUENCE SEQ_ITME;
--CREATE TABLE TBL_ITME(
--	ID NUMBER CONSTRAINT PK_ITEM PRIMARY KEY,
--	ITME_NAME VARCHAR2(255) NOT NULL,
--	ITME_PRICE NUMBER NOT NULL,
--	ITME_STOCK NUMBER DEFAULT 999,
--	ITEM_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--	COMPANY_ID NUMBER NOT NULL,
--	CONSTRAINT FK_ITEM_COMPANY FOREIGN KEY(COMPANY_ID)
--	REFERENCES TBL_COMPANY(ID)
--);
--
--
---- 사용자 정보 TBL_USER
---- 이름, 주소, 전화번호
--CREATE SEQUENCE SEQ_USER;
--CREATE TABLE TBL_USER(
--	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
--	USER_NAME VARCHAR2(255) NOT NULL,
--	USER_ADDRESS VARCHAR2(255) NOT NULL,
--	USER_PHONE VARCHAR2(255) NOT NULL,
--	USER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);
--
--
---- 사용자 카드 정보 (결제 시 결제 정보 저장 가능) TBL_CARD
---- 카드번호, 카드사, 회원 정보가
--CREATE SEQUENCE SEQ_CARD;
--CREATE TABLE TBL_CARD(
--	ID NUMBER CONSTRAINT PK_CARD PRIMARY KEY,
--	CARD_NUMBER CHAR(30) NOT NULL UNIQUE,
--	CARD_COMPANY CHAR(10) NOT NULL,
--	CARD_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--	USER_ID NUMBER NOT NULL,
--	CONSTRAINT FK_CARD_USER FOREIGN KEY(USER_ID)
--	REFERENCES TBL_USER(ID)
--);
--
--
---- 결제 시 사용자 정보와 기업의 정보, 결제한 카드의 정보 모두 필요하며, TBL_PAYMENT
---- 누가 어떤 상품을 어떠한 결제 수단으로 주문을 했는지
---- 상품에는 어떤 회사에서 판매를 하는지 녹여져 있음
---- 그러나 유저는 여러개의 카드를 가질 수 있기에 어떠한 카드로 주문을 했는지 정도는 넣어줘야 함
----   상품의 정보
--CREATE SEQUENCE SEQ_ORDER;
--CREATE TABLE TBL_ORDER(
--	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
--	ORDER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--	ORDER_NUMBER NUMBER NOT NULL,
--	ORDER_ITEM_COUNT NUMBER NOT NULL,
--	USER_ID NUMBER NOT NULL,
--	ITEM_ID NUMBER NOT NULL,
--	CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
--	REFERENCES TBL_USER(ID),
--	CONSTRAINT FK_ORDER_ITEM FOREIGN KEY(ITEM_ID)
--	REFERENCES TBL_ITME(ID)
--);
--
--
---- 영수증
---- 영수증에 카드 번호는 직접 기입해서 결제 시 해당 정보를 적거나
---- 유저 카드 정보를 불러왔다면 해당 카드 번호를 추출 해서 적게 함
---- 영수증은 각 상품 주문번호 별로 구매가 이루어진 카드 번호, 승인번호, 주문일자 가 나와야 함
---- 전자상거래법에 의해서 결제 주문 내역은 5년 보관
---- 유저가 탈퇴를 하거나, 유저가 저장된 카드를 변경하거나 더이상 안쓰게 되더라도 일정 기간 동안
---- 결제 내역을 보관 해야함
--CREATE SEQUENCE SEQ_RECEIPT;
--CREATE TABLE TBL_RECEIPT(
--	ID NUMBER CONSTRAINT PK_RECEIPT PRIMARY KEY,
--	RECEIPT_CARD_NUMBER CHAR(30) NOT NULL,
--	RECEIPT_APPROVAL_NUMBER CHAR(15) NOT NULL,
--	RECEIPT_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--	ORDER_ID NUMBER NOT NULL UNIQUE,
--	CONSTRAINT FK_RECEIPT_ORDER FOREIGN KEY(ORDER_ID)
--	REFERENCES TBL_ORDER(ID)
--);
--
--
---- DML
---- DATE : 7BYTE / TIMESTAMP: 11BYTE
--CREATE SEQUENCE SEQ_MEMBER;
--CREATE TABLE TBL_MEMBER(
--	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
--	MEMBER_NAME VARCHAR2(255) NOT NULL,
--	MEMBER_AGE NUMBER,
--	MEMBER_ADDRESS VARCHAR2(255) NOT NULL,
--	MEMBER_PHONE VARCHAR2(255),
--	MEMBER_GENDER CHAR(5),
--	MEMBER_CREATE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--	MEMBER_CREATE_DATE DATE DEFAULT SYSDATE
--);
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_PHONE, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '홍길동', 20, '서울시 강남구', '010-0000-0000', '남');
--
--INSERT INTO TBL_MEMBER
--VALUES(SEQ_MEMBER.NEXTVAL, '장보고', 30, '서울시 종로구', '010-4567-7890', '남', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '이순신', 40, '경기도 성남시', '남');
--
---- 김영희, 25살, 서울시 영등포구
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '김영희', 25, '서울시 영등포구', '여');
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '김철수', 35, '서울시 종로구', '남');
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '이규학', 28, '경기도 하남시', '남');
--
--INSERT INTO TBL_MEMBER(ID, MEMBER_NAME, MEMBER_AGE, MEMBER_ADDRESS, MEMBER_GENDER)
--VALUES(SEQ_MEMBER.NEXTVAL, '써니', 33, '경기도 남양주시', '남');
--
--
--
--UPDATE TBL_MEMBER 
--SET MEMBER_GENDER = 'W'
--WHERE ID = 4;
--
--
---- 이름이 홍길동인 사람의 전화번호를 010-4456-7788로 변경
--UPDATE TBL_MEMBER 
--SET MEMBER_PHONE = '010-4556-7788'
--WHERE MEMBER_NAME = '홍길동';
--
---- 서울시 영등포구에 거주중인 사람의 데이터 삭제
--DELETE FROM TBL_MEMBER
--WHERE MEMBER_ADDRESS = '서울시 영등포구';
--
---- DELETE DROP 
--DELETE FROM TBL_MEMBER
--WHERE ID = 3;
--
--
---- 나이가 20대 인 사용자 정보 조회
--SELECT * FROM TBL_MEMBER 
--WHERE MEMBER_AGE >= 20 AND MEMBER_AGE <= 29;
--
--SELECT * FROM TBL_MEMBER
--WHERE MEMBER_GENDER = '남';
--
--
--SELECT MEMBER_NAME, MEMBER_AGE FROM TBL_MEMBER
--WHERE MEMBER_GENDER = '남';
--
--
--/*
-- * 
-- * LIKE: 포함된 문자열 값을 찾고, 문자의 개수도 제한을 줄 수 있다.
-- * 
-- * %: 모든 것
-- * _: 글자 수
-- * 
-- * 예시
-- '%A' : A로 끝나는 모든 값(NDFLSNJFA, 123NFJA, ...)
-- 'A%' : A로 시작하는 모든 값(AA, ANDKFS, AJD, ...)
-- 'A__' : A로 시작하며 3글자인 값(ABC, AAA, ADD, ...)
-- '_A' : A로 끝나며 2글자인 값(FA, CA, DA, ...)
-- '%A%' : A가 포함된 값(APPLE, BANANA, TASK, ...)
-- * 
-- * */
--
---- 서울에 살고 있는 사용자 조회
-- SELECT *
-- FROM TBL_MEMBER 
-- WHERE MEMBER_ADDRESS LIKE '서울%';
--
---- 시 에 살고 있는
--SELECT *
--FROM TBL_MEMBER 
--WHERE MEMBER_ADDRESS LIKE '%시';
--
--
----종로에 살고 있는 사용자 나이 조회
--SELECT MEMBER_AGE
--FROM TBL_MEMBER 
--WHERE MEMBER_ADDRESS LIKE '%종로%';
--
--
---- NULL 타입 비교 하려면 IS 적어야 함
--SELECT *
--FROM TBL_MEMBER 
--WHERE MEMBER_PHONE IS NOT NULL;
--
--
---- 경기도에 살고 있지 아니한 사용자 이름
--SELECT MEMBER_NAME
--FROM TBL_MEMBER 
--WHERE MEMBER_ADDRESS NOT LIKE '%경기%';
--
--
---- 가상 테이블: DUAL
---- 하나의 행 하나의 열 으로 하면 값으로 사용 가능
--SELECT SYSDATE FROM DUAL;
--
---- 같은 컬럼을 여러번 조회할 수 있다
---- ALIAS 별칭: 최종 테이블의 속성 이름을 변경할 수 있다.
---- "" 는 별칭을 붙이기 위한 목적의 마커
--SELECT MEMBER_NAME "이름", MEMBER_AGE "회원 나이", MEMBER_AGE - 1 "만나이"
--FROM TBL_MEMBER;
---- 이때 만들어진 만 나이는 파생 변수임 (없던거를 만들어 낸거)
--
---- 연결(||)
--SELECT 'ABCD' || '님' FROM DUAL;
--SELECT CONCAT('A', 'A') FROM DUAL;
--SELECT CONCAT('A', NULL) FROM DUAL;
---- NULL 은 무시됨
--
--SELECT MEMBER_NAME || ' 님' "이름"
--FROM TBL_MEMBER;
--
--SELECT MEMBER_AGE || '살' "나이"
--FROM TBL_MEMBER;
--
--SELECT CONCAT(MEMBER_AGE, '살') "나이"
--FROM TBL_MEMBER;
--
--SELECT LENGTH(MEMBER_ADDRESS), MEMBER_ADDRESS
--FROM TBL_MEMBER;
--
--
---- 글자 자르기 SUBSTRING
---- 오라클은 인덱스 1부터 시작
--SELECT SUBSTR('HELLO WORLD', 6, 2)
--FROM TBL_MEMBER;
--
--
--SELECT MEMBER_AGE + 1 FROM TBL_MEMBER;
--SELECT MEMBER_AGE - 1 FROM TBL_MEMBER;
--SELECT MEMBER_AGE * 10 FROM TBL_MEMBER;
--SELECT CEIL(MEMBER_AGE / 3)  FROM TBL_MEMBER;
--SELECT FLOOR(MEMBER_AGE / 3)  FROM TBL_MEMBER;
--SELECT ROUND(MEMBER_AGE / 3)  FROM TBL_MEMBER;
--
--
---- 나머지 찾기
--SELECT MOD(MEMBER_AGE, 3)  FROM TBL_MEMBER;
--SELECT * FROM TBL_MEMBER;
--
--
---- 시험에 잘나오는거
---- NULL
---- NULL 과 연산 되면 무조건 다 NULL
--
--
---- 평균
---- 최대값
---- 최소값
---- 총합
--
--/*집계 함수
-- * 
-- * 평균 AVG()
-- * 최대값 MAX()
-- * 최소값 MIN()
-- * 총 합 SUM()
-- * 개수 COUNT()
-- * 
-- * */
--
--CREATE SEQUENCE SEQ_PRODUCT;
--CREATE TABLE TBL_PRODUCT(
--	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
--	PRODUCT_NAME VARCHAR2(255) NOT NULL,
--	PRODUCT_PRICE NUMBER DEFAULT 0,
--	PRODUCT_STOCK NUMBER DEFAULT 999,
--	PRODUCT_CREATE_AT DATE
--);
--
--
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '규학이의 텀블러', 15000, 10, TO_DATE('2026-01-12 11:25', 'YYYY-MM-DD HH:mi'));
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '소훈이의 마스크', 20000, 60, TO_DATE('2026-02-20 12:50', 'YYYY-MM-DD HH:mi'));
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '써니의 마음', 100000, 2, TO_DATE('2025-10-07 11:25', 'YYYY-MM-DD HH:mi'));
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '하영이의 아이폰', 200000, 1, TO_DATE('2026-03-03 11:25', 'YYYY-MM-DD HH:mi'));
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '유중의 미', 500000, 5, TO_DATE('2026-02-20 16:00', 'YYYY-MM-DD HH24:mi'));
--INSERT INTO TBL_PRODUCT
--VALUES(SEQ_PRODUCT.NEXTVAL, '규호의 코카콜라', 200000, 30, TO_DATE('2026-02-02 15:00', 'YYYY-MM-DD HH24:mi'));
--
--
---- 가장 비싼 상품은/???
---- 그룹 함수, 집계 함수는 WHERE 절에서 사용이 불가능하다.
---- MAX 는 하나의 값 연산 가능함
--SELECT MAX(PRODUCT_PRICE)
--FROM TBL_PRODUCT;
--
---- 상품이 모두 판매 됬을 때 가격
--SELECT SUM(PRODUCT_PRICE * PRODUCT_STOCK)
--FROM TBL_PRODUCT;
--
---- 판매 중 상품의 평균 가격
--SELECT AVG(PRODUCT_PRICE) FROM TBL_PRODUCT;
--
--
--SELECT * FROM TBL_PRODUCT;
---- 써니의 마음, 유중의 미, 규혁이의 텀블러 평균
--SELECT *
--FROM TBL_PRODUCT
--WHERE PRODUCT_NAME LIKE '%써니%' 
--OR PRODUCT_NAME LIKE '%유중%'
--OR PRODUCT_NAME LIKE '%규학%';
--
--
--SELECT TO_CHAR(AVG(PRODUCT_PRICE), '999,999') || '원'  "평균 가격"
--FROM TBL_PRODUCT
--WHERE PRODUCT_NAME LIKE '%써니%' 
--OR PRODUCT_NAME LIKE '%유중%'
--OR PRODUCT_NAME LIKE '%규학%';
--
---- WHERE IN (나열해서 할 수도 있음)
--
---- 
--
---- 집계함수에 NULL 이 들어가면 결과는 0이다.
--SELECT COUNT(*) FROM TBL_PRODUCT;
--
---- ORDER BY: 정렬 (ASC 오름차순이 기본값)
--SELECT *
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC;
--
--
---- 최신 등록순
--SELECT *
--FROM TBL_PRODUCT
--ORDER BY ID DESC;
--
--
---- 날짜의 연산
---- 더하기는 기본적으로 일자 별로 계산
--SELECT PRODUCT_CREATE_AT, PRODUCT_CREATE_AT + 1
--FROM TBL_PRODUCT;
--
--
---- 가장 비싼 상품 조회
---- 1. 정렬 하고 위에서 부터 가져오기
--SELECT *
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC
--FETCH FIRST 3 ROWS ONLY;
--
---- OFFSET
--SELECT *
--FROM TBL_PRODUCT
--ORDER BY PRODUCT_PRICE DESC
--OFFSET (1-1)*3 ROW FETCH NEXT 3 ROWS ONLY;


--SELECT MAX(PRODUCT_PRICE) - 10000 FROM TBL_PRODUCT
--GROUP BY 


/*
 * GROUP BY: ~별
 * 
 * GROUP BY 컬럼명 HAVING 조건식
 * 
 * */

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
   ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
   PRODUCT_NAME VARCHAR2(255) NOT NULL,
   PRODUCT_PRICE NUMBER DEFAULT 0,
   PRODUCT_STOCK NUMBER DEFAULT 999
);


SELECT * FROM TBL_PRODUCT;

INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 2000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 3000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 4000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 6000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 5000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 2000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 60);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 2000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 3000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '지우개', 1000, 30);

INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 5000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 4000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 2000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 1000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 5000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 6000, 80);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 2000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 5000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 3000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 2000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '모자', 1000, 40);


INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 4000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 1000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 50);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 40);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 1000, 20);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 2000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 30);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 3000, 10);
INSERT INTO TBL_PRODUCT
VALUES(SEQ_PRODUCT.NEXTVAL, '바지', 5000, 10);


--갯수가 3개 이상인 상품 조회
SELECT 
	PRODUCT_NAME, 
	PRODUCT_PRICE,
	COUNT(PRODUCT_NAME)
FROM TBL_PRODUCT
GROUP BY PRODUCT_NAME, PRODUCT_PRICE
HAVING PRODUCT_PRICE >= 5000;

-- 상품의 가격대 별 기대수익
SELECT 
	PRODUCT_NAME "상품명",
	TO_CHAR(PRODUCT_PRICE, '999,999') || '원' "가격대",
	COUNT(PRODUCT_NAME) "갯수",
	SUM(PRODUCT_PRICE) "기대수익"
FROM TBL_PRODUCT
GROUP BY PRODUCT_NAME, PRODUCT_PRICE;

SELECT 
	SUM(PRODUCT_PRICE) "기대수익"
FROM TBL_PRODUCT;




