CREATE SEQUENCE SEQ_MEMBER;
CREATE TABLE TBL_MEMBER(
	ID NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
	MEMBER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255),
	MEMBER_NAME VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) UNIQUE NOT NULL,
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 999
);

-- 주문
CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_COMMENT VARCHAR2(255),
	ORDER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);


-- 게시글
CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
	POST_TITLE VARCHAR2(255) NOT NULL,
	POST_CONTENT VARCHAR2(255) NOT NULL,
	POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	CONSTRAINT FK_POST_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);


-- 댓글
CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
	ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
	REPLY_CONTENT VARCHAR2(255) NOT NULL,
	REPLY_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	POST_ID NUMBER,
	MEMBER_ID NUMBER,
	CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
	REFERENCES TBL_POST(ID),
	CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);


-- 아이들
CREATE SEQUENCE SEQ_CHILDREN;
CREATE TABLE TBL_CHILDREN(
	ID NUMBER CONSTRAINT PK_CHILDREN PRIMARY KEY,
	CHILDREN_NAME VARCHAR2(255) NOT NULL,
	CHILDREN_AGE NUMBER NOT NULL,
	CHILDREN_GENDER VARCHAR2(255) NOT NULL
);

-- 학부모
-- 아이는 엄마 아빠 혹은 유관 보호자가 존재
-- 는 ㅇㅇ엄마 입니다. ㅁㅁ 는 ㅇㅇ 아빠 입니다. ㄱㄱ 는 ㅇㅇ 할머니 입니다.
-- 아이 : 학부모 = 1 : N 관계
CREATE SEQUENCE SEQ_PARENT;
CREATE TABLE TBL_PARENT(
	ID NUMBER CONSTRAINT PK_PARENT PRIMARY KEY,
	PARENT_NAME VARCHAR2(255) NOT NULL,
	PARENT_AGE NUMBER NOT NULL,
	PARENT_ADDRESS VARCHAR2(255) NOT NULL,
	PARENT_PHONE VARCHAR2(255) NOT NULL,
	PARENT_GENDER VARCHAR2(255) NOT NULL,
	CHILDREN_ID NUMBER,
	CONSTRAINT FK_PARENT_CHILDREN FOREIGN KEY(CHILDREN_ID)
	REFERENCES TBL_CHILDREN(ID)
);

-- 체험학습 (로우 데이터)
CREATE SEQUENCE SEQ_SOPUNG;
CREATE TABLE TBL_SOPUNG(
	ID NUMBER CONSTRAINT PK_SOPUNG PRIMARY KEY,
	SOPUNG_TITLE VARCHAR2(255) NOT NULL,
	SOPUNG_CONTENT VARCHAR2(255) NOT NULL
);

-- 체험학습 신청 테이블
CREATE SEQUENCE SEQ_SP_ENROLL;
CREATE TABLE TBL_SP_ENROLL(
	ID NUMBER CONSTRAINT PK_SP_ENROLL PRIMARY KEY,
	SP_ENROLL_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CHILDREN_ID NUMBER,
	SOPUNG_ID NUMBER,
	CONSTRAINT FK_SP_ENROLL_CHILDREN FOREIGN KEY(CHILDREN_ID)
	REFERENCES TBL_CHILDREN(ID),
	CONSTRAINT FK_SP_ENROLL_SOPUNG FOREIGN KEY(SOPUNG_ID)
	REFERENCES TBL_SOPUNG(ID)
);


-- 체험학습 이미지 URL 을 담는 테이블
-- 하나의 체험학습은 여러개의 이미지를 가질 수 있음
CREATE SEQUENCE SEQ_SP_IMAGE;
CREATE TABLE TBL_SP_IMAGE(
	ID NUMBER CONSTRAINT PK_SP_IMAGE PRIMARY KEY,
	SP_IMAGE_URL VARCHAR2(255) NOT NULL,
	SOPUNG_ID NUMBER,
	CONSTRAINT FK_SP_IMAGE_SOPUNG FOREIGN KEY(SOPUNG_ID)
	REFERENCES TBL_SOPUNG(ID)
);


--   요구사항
--   안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
--   광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)입니다.
--   광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
--   기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다.

CREATE SEQUENCE SEQ_BIG_CT;
CREATE TABLE TBL_BIG_CT(
	ID NUMBER CONSTRAINT PK_BIG_CT PRIMARY KEY,
	BIG_CT_NAME VARCHAR2(255) NOT NULL 
);

CREATE SEQUENCE SEQ_MID_CT;
CREATE TABLE TBL_MID_CT(
	ID NUMBER CONSTRAINT PK_MID_CT PRIMARY KEY,
	MID_CT_NAME VARCHAR2(255) NOT NULL,
	BIG_CT_ID NUMBER,
	CONSTRAINT FK_MID_CT_BIG_CT FOREIGN KEY(BIG_CT_ID)
	REFERENCES TBL_BIG_CT(ID)
);

CREATE SEQUENCE SEQ_SMALL_CT;
CREATE TABLE TBL_SMALL_CT(
	ID NUMBER CONSTRAINT PK_SMALL_CT PRIMARY KEY,
	SMALL_CT_NAME VARCHAR2(255) NOT NULL,
	MID_CT_ID NUMBER,
	CONSTRAINT FK_SMALL_CT_MID_CT FOREIGN KEY(MID_CT_ID)
	REFERENCES TBL_MID_CT(ID)
);


-- 광고주 TBL_CUSTOMER
-- 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)
CREATE SEQUENCE SEQ_CUSTOMER;
CREATE TABLE TBL_CUSTOMER(
	ID NUMBER CONSTRAINT PK_CUSTOMER PRIMARY KEY,
	CUSTOMER_NAME VARCHAR2(255) NOT NULL,
	CUSTOMER_PHONE VARCHAR2(255) NOT NULL,
	CUSTOMER_TYPE CHAR(10) NOT NULL
);


-- 광고 TBL_AD
-- 제목, 내용
CREATE SEQUENCE SEQ_AD;
CREATE TABLE TBL_AD(
	ID NUMBER CONSTRAINT PK_AD PRIMARY KEY,
	AD_TITLE VARCHAR2(255) NOT NULL,
	AD_CONTENT VARCHAR2(255) NOT NULL
);

-- 광고 신청 TBL_ENROLL_AD
--CREATE AT, USER FK, 대 카테고리, 중 카테고리, 소 키테고리 에는 광고 ID
CREATE SEQUENCE SEQ_ENROLL_AD;
CREATE TABLE TBL_ENROLL_AD(
	ID NUMBER CONSTRAINT PK_ENROLL_AD PRIMARY KEY,
	ENROLL_AD_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ENROLL_AD_BIG_CT NUMBER,
	ENROLL_AD_MID_CT NUMBER,
	ENROLL_AD_SMALL_CT NUMBER,
	CUSTOMER_ID NUMBER,
	CONSTRAINT FK_ENROLL_AD_BIG_CT_AD FOREIGN KEY(ENROLL_AD_BIG_CT)
	REFERENCES TBL_AD(ID),
	CONSTRAINT FK_ENROLL_AD_MID_CT_AD FOREIGN KEY(ENROLL_AD_MID_CT)
	REFERENCES TBL_AD(ID),
	CONSTRAINT FK_ENROLL_AD_SMALL_CT_AD FOREIGN KEY(ENROLL_AD_SMALL_CT)
	REFERENCES TBL_AD(ID),
	CONSTRAINT FK_ENROLL_AD_CHILDREN FOREIGN KEY(CUSTOMER_ID)
	REFERENCES TBL_CUSTOMER(ID)
);





