/*
 * GROUP BY부터 생각을 많이 해야한다.
 * FROM -> WHERE -> GROUP BY -> HAVING -> SELECT > ORDER BY
 * 
*/

SELECT * FROM TBL_POST;
SELECT * FROM TBL_REPLY;
SELECT * FROM TBL_USER;

-- FK 가 있는 테이블부터 시작해서 JOIN 을 하는게 더 편함
SELECT TBP.*, TBU.USER_EMAIL 
FROM TBL_POST TBP
JOIN TBL_USER TBU
ON TBP.USER_ID  = TBU.ID;


SELECT * FROM TBL_REPLY;

SELECT TBR.REPLY_CONTENT , TBP.POST_TITLE 
FROM TBL_REPLY TBR
JOIN TBL_POST TBP 
ON TBR.POST_ID = TBP.ID;


-- 유저, 댓글 조인
-- 댓글의 작성자와 댓글 내용을 조회 하십시오
SELECT TBU.USER_EMAIL "작성자", TBR.REPLY_CONTENT "댓글 내용"
FROM TBL_REPLY TBR
JOIN TBL_USER TBU 
ON TBR.USER_ID = TBU.ID;


-- 3개
-- 게시글 제목,  댓글 내용, 작성자
SELECT TBP.POST_TITLE, TBR.REPLY_CONTENT , TBU.USER_EMAIL 
FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID 
JOIN TBL_POST TBP 
ON TBR.POST_ID = TBP.ID
WHERE TBP.POST_TITLE LIKE '%유중의 미%';


SELECT DISTINCT TBP.POST_TITLE
FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID 
JOIN TBL_POST TBP 
ON TBR.POST_ID = TBP.ID
WHERE TBP.POST_TITLE LIKE '%유중의 미%';


-- 댓글이 2개 이상 달린 게시글의 작성자 이메일, 주소를 조회하기

--먼저 댓글이 2개 이상 달린 게시글 조회
SELECT POST_ID, COUNT(POST_ID)
FROM TBL_REPLY
GROUP BY POST_ID
HAVING COUNT(POST_ID) >= 2;

--해당 게시글 아이디 추출
SELECT POST_ID
FROM TBL_REPLY
GROUP BY POST_ID
HAVING COUNT(POST_ID) >= 2;

SELECT DISTINCT TBU.USER_EMAIL, TBU.USER_ADDRESS 
FROM TBL_POST TBP
JOIN TBL_USER TBU 
ON TBP.USER_ID = TBU.ID
WHERE TBP.ID IN (
	SELECT POST_ID
	FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) >= 2
);

-- 해당 조건을 만족하는 게시글의 댓글들을 추출
SELECT *
FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID
WHERE TBR.POST_ID IN(
	SELECT POST_ID
	FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) >= 2
);

-- 조건에 맞는 게시글에 달린 댓글의 작성자의 이메일, 거주 주소 추출
SELECT DISTINCT TBU.USER_EMAIL, TBU.USER_ADDRESS 
FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID
WHERE TBR.POST_ID IN(
	SELECT POST_ID
	FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) >= 2
);


-- 내용에 뀨트북이 들어간 게시글의 달린 댓글 조회
SELECT * FROM TBL_REPLY;

-- 내용에 뀨트북이 들어간 게시글 조회하기
SELECT * FROM TBL_POST
WHERE POST_CONTENT LIKE '%뀨트북%' OR POST_TITLE LIKE '%뀨트북%';

SELECT ID FROM TBL_POST
WHERE POST_CONTENT LIKE '%뀨트북%' OR POST_TITLE LIKE '%뀨트북%';

SELECT * FROM TBL_REPLY
WHERE POST_ID IN (
	SELECT ID FROM TBL_POST
	WHERE POST_CONTENT LIKE '%뀨트북%' OR POST_TITLE LIKE '%뀨트북%'
);

SELECT REPLY_CONTENT FROM TBL_REPLY
WHERE POST_ID IN (
	SELECT ID FROM TBL_POST
	WHERE POST_CONTENT LIKE '%뀨트북%' OR POST_TITLE LIKE '%뀨트북%'
);


-- 내용에 포도가 들어간 글을 작성한 작성자의 이메일 조회
-- 1. 내용에 포도가 들어가는 글을 먼저 찾기
SELECT * FROM TBL_POST
WHERE POST_CONTENT LIKE '%포도%';

SELECT USER_ID FROM TBL_POST
WHERE POST_CONTENT LIKE '%포도%';

-- 포도가 들어간 글을 작성 한 유저를 찾아서 이메일을 조회하기
SELECT * FROM TBL_USER
WHERE ID IN (
	SELECT USER_ID FROM TBL_POST
	WHERE POST_CONTENT LIKE '%포도%'
);

SELECT USER_EMAIL FROM TBL_USER
WHERE ID IN (
	SELECT USER_ID FROM TBL_POST
	WHERE POST_CONTENT LIKE '%포도%'
);


-- 2000년생 유저가 작성한 댓글 조회
SELECT * FROM TBL_REPLY;

-- 2000년대 유저 먼저 조회
SELECT * FROM TBL_USER;

SELECT ID FROM TBL_USER
WHERE USER_BIRTH >= TO_DATE('2000-01-01', 'YYYY-MM-DD');

SELECT TBU.USER_EMAIL, TBR.REPLY_CONTENT FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID
WHERE TBR.USER_ID IN (
	SELECT ID FROM TBL_USER
	WHERE USER_BIRTH >= TO_DATE('2000-01-01', 'YYYY-MM-DD')
);

SELECT TBU.USER_EMAIL, TBR.REPLY_CONTENT FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID
WHERE TBU.USER_BIRTH >= TO_DATE('2000-01-01', 'YYYY-MM-DD')
	AND TBU.USER_BIRTH < TO_DATE('2001-01-01', 'YYYY-MM-DD');




-- 가장 나이가 어린 사용자가 작성한 게시글 조회
-- 먼저 가장 나이가 어린 사용자 추출
-- FETCH FIRST 1 ROWS ONLY 도 사용 가능
-- JOIN 에 들어가는 거는 테이블 (테이블 명 혹은 쿼리로 만들어진 테이블을 넣는거도 가능)
-- ROWNUM 도 가능
 SELECT * FROM TBL_USER;
 SELECT MAX(USER_BIRTH) FROM TBL_USER;

SELECT TBU.USER_EMAIL "작성자" , TBP.POST_TITLE "게시글 제목", TBP .POST_CONTENT "게시글 내용"
FROM TBL_POST TBP
JOIN TBL_USER TBU
ON TBP.USER_ID = TBU.ID
WHERE TBU.USER_BIRTH = (
		SELECT MAX(USER_BIRTH) FROM TBL_USER
);



-- 주소가 '구'로 끝나는 유저가 작성한 게시글에 달린 모든 댓글 조회
-- 1. 주소가 구 로 끝나는 유저 찾기
SELECT * FROM TBL_USER;

SELECT * FROM TBL_USER
WHERE USER_ADDRESS LIKE '%구';


--2. 댓글 정보를 가져오 되 작성자 정보 및 게시글 정보 까지 JOIN 해서 가져오기
SELECT * FROM TBL_REPLY;

SELECT * FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID 
JOIN TBL_POST TBP
ON TBR.POST_ID = TBP.ID;

-- 3. 여기서 주소가 구로 끝나는 유저가 작성을 한 게시글에 달린 댓글만 보기
SELECT *
FROM TBL_REPLY TBR
JOIN TBL_USER TBU
ON TBR.USER_ID = TBU.ID 
JOIN TBL_POST TBP
ON TBR.POST_ID = TBP.ID
WHERE TBP.USER_ID IN(
	SELECT ID FROM TBL_USER
	WHERE USER_ADDRESS LIKE '%구'
);

-- 수정
SELECT TBR.REPLY_CONTENT 
FROM TBL_REPLY TBR
JOIN TBL_POST TBP
ON TBR.POST_ID = TBP.ID
WHERE TBP.USER_ID IN(
	SELECT ID FROM TBL_USER
	WHERE USER_ADDRESS LIKE '%구'
);





-- 평균 댓글 개수보다 작게 달린 게시글을 작성한 유저 조회
-- 1. 게시글 별로 댓글 수를 모으기
SELECT * FROM TBL_REPLY;

SELECT POST_ID, COUNT(POST_ID) 
FROM TBL_REPLY
GROUP BY POST_ID;

-- 2. 게시글 전체으 평균 댓글 수 구하기
SELECT AVG(COUNT(POST_ID)) 
FROM TBL_REPLY
GROUP BY POST_ID;

-- 3. 평균 댓글 수 보다 댓글 수가 적은 게시글 추출
SELECT POST_ID, COUNT(POST_ID) 
FROM TBL_REPLY
GROUP BY POST_ID
HAVING COUNT(POST_ID) <= (
	SELECT AVG(COUNT(POST_ID)) 
	FROM TBL_REPLY
	GROUP BY POST_ID
);

SELECT POST_ID
FROM TBL_REPLY
GROUP BY POST_ID
HAVING COUNT(POST_ID) <= (
	SELECT AVG(COUNT(POST_ID)) 
	FROM TBL_REPLY
	GROUP BY POST_ID
);

-- 4. 게시글 과 유저를 조인 해서 게시글을 작성한 유저 조회
SELECT *
FROM TBL_POST TBP
JOIN TBL_USER TBU
ON TBP.USER_ID = TBU.ID;

-- 5. 댓글이 평균 수 이상인 게시글을 작성한 유저 정보 최종 추출
SELECT *
FROM TBL_POST TBP
JOIN TBL_USER TBU
ON TBP.USER_ID = TBU.ID
WHERE TBP.ID IN (
	SELECT POST_ID
	FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) < (
		SELECT AVG(COUNT(POST_ID)) 
		FROM TBL_REPLY
		GROUP BY POST_ID
	)
);

SELECT 
	TBP.POST_TITLE "게시글 제목",
	TBP.POST_CONTENT "게시글 내용",
	TBU.*
FROM TBL_POST TBP
JOIN TBL_USER TBU
ON TBP.USER_ID = TBU.ID
WHERE TBP.ID IN (
	SELECT POST_ID
	FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) < (
		SELECT AVG(COUNT(POST_ID)) 
		FROM TBL_REPLY
		GROUP BY POST_ID
	)
);








