-- 인터프리트 언어
-- 마지막에 ;
-- 대문자 사용
--
--
--
--SELECT SYSDATE FROM DUAL;
--
--CREATE TABLE 테이블명(
--	컬럼명 타입 제약조건1, 제약조건2,
--	컬럼명 타입 제약조건1, 제약조건2,
--	컬럼명 타입 제약조건1, 제약조건2,
--);
--
--CREATE TABLE TBL_TEST(
--	ID NUMBER CONSTRAINT PK_TEST PRIMARY KEY,
--	TEST_NAME VARCHAR2(255),
--	TEST_AGE NUMBER
--);
--
--SELECT * FROM TBL_TEST;
--
-- 동물
-- 이름(NAME), 나이(AGE), 종류(SPECIES), 생일(BIRTH_DAY) 
--CREATE TABLE TBL_ANIMAL(
--	ID NUMBER CONSTRAINT PK_ANIMAL PRIMARY KEY,
--	ANIMAL_NAME VARCHAR2(255),
--	ANIMAL_AGE NUMBER,
--	ANIMAL_SPECIES VARCHAR2(255),
--	ANIMAL_BIRTH_DAY DATE
--);
--SELECT * FROM TBL_ANIMAL;
--
-- 게시판(POST)
-- 글제목, 글내용, 작성시간
--
--CREATE SEQUENCE SEQ_POST;
--CREATE TABLE TBL_POST(
--	ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
--	POST_TITLE VARCHAR2(255),
--	POST_CONTENT VARCHAR2(255),
--	POST_CREATE_AT TIMESTAMP
--);
--
--SELECT * FROM TBL_POST
--
-- ALTER
-- 컬럼 추가 (ADD)
--
-- 먹이 컬럼 추가(FEED)
-- ALTER TABLE TBL_ANIMAL ADD 컬럼명 타입;
--ALTER TABLE TBL_ANIMAL ADD ANIMAL_FEED VARCHAR2(255);
--
--ALTER TABLE TBL_ANIMAL MODIFY ANIMAL_FEED NUMBER;
--ALTER TABLE TBL_ANIMAL MODIFY ANIMAL_FEED VARCHAR2(255);
--
-- BIRTHDAY -> 타입스탬프 형태로 변경
--ALTER TABLE TBL_ANIMAL MODIFY ANIMAL_BIRTH_DAY TIMESTAMP;
--
-- 컬럼 명 변환 (RENAME COLUMN 기존 컬럼명 TO 바꿀 컬럼 명)
--ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_BIRTH_DAY TO ANIMAL_BIRTH;
--
-- ANIMAL_NAME -> ANIMAL_OWNER
--ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_NAME TO ANIMAL_OWNER;
--
-- ANIMAL 테이블 이름을 -> TBL_PERSON 으로 변경
--ALTER TABLE TBL_ANIMAL RENAME TO TBL_PERSON;
--
--SELECT * FROM TBL_PERSON;
--
-- DROP TABLE TBL_TEST; 테이블 전체 삭제
-- TRUNCATE 테이블은 놔두고 데이터만 날리는거
--
--
-- 테이블 생성과 제약조건
-- TBL_USER 
-- ID, 
-- 이메일(USER_EMAIL), 
-- 비밀번호(USER_PASSWORD), 
-- 이름(USER_NAME), 
-- 휴대폰(USER_PHONE)
-- 회원가입날자(USER_CREATE_AT)
--
--CREATE SEQUENCE SEQ_USER;
--CREATE TABLE TBL_USER(
--	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
--	USER_EMAIL VARCHAR2(255) UNIQUE NOT NULL,
--	USER_PASSWORD VARCHAR2(255) NOT NULL,
--	USER_NAME VARCHAR2(255),
--	USER_PHONE VARCHAR2(255) NOT NULL,
--	USER_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
--);


-- 자동차 테이블(TBL_CAR)
-- 이름 (NAME), 브랜드(BRAND), 가격(PRICE), 컬러(COLOR), 출고일(CREATE_AT) 
-- 인승(SEATER)
-- 제약조건

CREATE SEQUENCE SEQ_CAR;
CREATE TABLE TBL_CAR(
	ID NUMBER CONSTRAINT PK_CAR PRIMARY KEY,
	CAR_NAME VARCHAR2(255) NOT NULL,
	CAR_BRAND VARCHAR(255) NOT NULL,
	CAR_PRICE NUMBER NOT NULL,
	CAR_COLOR VARCHAR2(255) NOT NULL,
	CAR_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CAR_SEATER NUMBER NOT NULL
);

-- 1. CAR_NAME 컬럼 이름 변경 -> CAR_MODEL
ALTER TABLE TBL_CAR RENAME COLUMN CAR_NAME TO CAR_MODEL;

-- 2. CAR_PRICE 타입 -> VARCHAR2(255)
ALTER TABLE TBL_CAR MODIFY CAR_PRICE VARCHAR2(255);
-- 만약 타입이 안바뀌면 삭제 한 다음에 추가 하는거도 가능

-- 3. COLOR 컬럼 삭제
ALTER TABLE TBL_CAR DROP COLUMN CAR_COLOR;


-- 제약조건을 수정
-- NOT NULL,
ALTER TABLE TBL_CAR MODIFY CAR_MODEL NULL;
ALTER TABLE TBL_CAR MODIFY CAR_MODEL NOT NULL;


-- ADD CONSTRAINT 라는 제약조천 추가 명령어 필요
-- UNIQUE
-- CAR_MODEL 에 UNIQUE 추가
ALTER TABLE TBL_CAR ADD CONSTRAINT UK_ UNIQUE (CAR_MODEL);
ALTER TABLE TBL_CAR DROP CONSTRAINT UK_;
-- ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY (ID);


-- DEFAULT 값 수정 삭제
-- 오라클은 값이 '' 싱글쿼터
ALTER TABLE TBL_CAR MODIFY CAR_BRAND DEFAULT '블랙';

-- 수정은 그냥 값 바꾸기
ALTER TABLE TBL_CAR MODIFY CAR_BRAND DEFAULT '레드';

-- 삭제
ALTER TABLE TBL_CAR MODIFY CAR_BRAND DEFAULT NULL;

-- 1. CAR_SEATER의 DEFAULT 값을 8로 변경
-- 2. CAR_BRAND UNIQUE 추가

ALTER TABLE TBL_CAR MODIFY CAR_SEATER DEFAULT 8;
ALTER TABLE TBL_CAR ADD CONSTRAINT UK_CAR_BRAND UNIQUE (CAR_BRAND);


SELECT * FROM TBL_CAR;


-- 관계
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
	ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
	USER_NAME VARCHAR2(255) NOT NULL,
	USER_ADDRESS VARCHAR2(255) NOT NULL,
	USER_PHONE VARCHAR2(255) DEFAULT '010-0000-0000'
);

CREATE SEQUENCE SEQ_ORDER;
CREATE TABLE TBL_ORDER(
	ID NUMBER CONSTRAINT PK_ORDER PRIMARY KEY,
	ORDER_PRODUCT_NAME VARCHAR2(255),
	ORDER_STOCK NUMBER DEFAULT 1,
	USER_ID NUMBER,
	CONSTRAINT FK_ORDER_USER FOREIGN KEY(USER_ID)
	REFERENCES TBL_USER(ID)
);



-- 상품 테이블(TBL_PRODUCT)
-- 상품 이름, 상품 가격, 상품 재고

-- 선물 테이블(TBL_GIFT)
-- 선물 주소, 선물 수량, 상품의 아이디

CREATE SEQUENCE SEQ_PRODUCT;
CREATE TABLE TBL_PRODUCT(
	ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY,
	PRODUCT_NAME VARCHAR2(255) NOT NULL,
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_STOCK NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_GIFT;
CREATE TABLE TBL_GIFT(
	ID NUMBER CONSTRAINT PK_GIFT PRIMARY KEY,
	GIFT_ADDRESS VARCHAR2(255) NOT NULL,
	GIFT_COUNT NUMBER NOT NULL,
	PRODUCT_ID NUMBER,
	CONSTRAINT FK_GIFT_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);




-- 정규화

