-- 서브쿼리
-- 게시판, 댓글
-- 유저(TBL_USER)
-- 이메일(EMAIL), 비밀번호(PASSWORD), 주소(ADDRESS), 생일(BIRTH)
CREATE SEQUENCE SEQ_USER;
CREATE TABLE TBL_USER(
   ID NUMBER CONSTRAINT PK_USER PRIMARY KEY,
   USER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
   USER_PASSWORD VARCHAR2(255),
   USER_ADDRESS VARCHAR2(255),
   USER_BIRTH DATE
);

-- 게시판(TBL_POST)
-- 제목(TITLE), 내용(CONTENT), 작성일(CREATE_AT)
CREATE SEQUENCE SEQ_POST;
CREATE TABLE TBL_POST(
   ID NUMBER CONSTRAINT PK_POST PRIMARY KEY,
   POST_TITLE VARCHAR2(255) NOT NULL,
   POST_CONTENT VARCHAR2(255) NOT NULL,
   POST_CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   USER_ID NUMBER,
   CONSTRAINT FK_POST_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID)
);

-- 댓글(TBL_REPLY)
-- 내용(CONTENT)
CREATE SEQUENCE SEQ_REPLY;
CREATE TABLE TBL_REPLY(
   ID NUMBER CONSTRAINT PK_REPLY PRIMARY KEY,
   REPLY_CONTENT VARCHAR2(255) NOT NULL,
   USER_ID NUMBER,
   POST_ID NUMBER,
   CONSTRAINT FK_REPLY_USER FOREIGN KEY(USER_ID)
   REFERENCES TBL_USER(ID),
   CONSTRAINT FK_REPLY_POST FOREIGN KEY(POST_ID)
   REFERENCES TBL_POST(ID)
);

-- 유저
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'hong1234@gmail.com', '1234', '경기도 구리시', '1995-03-03');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'jang1234@gmail.com', '1234', '서울시 강남구', '2000-11-14');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'lee1234@gmail.com', '4567', '서울시 종로구', '2003-01-17');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'kcs1234@gmail.com', '1234', '서울시 떡잎마을', '1995-07-07');
INSERT INTO TBL_USER
VALUES(SEQ_USER.NEXTVAL, 'kyh1234@gmail.com', '1234', '서울시 떡잎마을', '1995-08-08');

-- 게시글
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '기분 좋은 금요일! 뀨트북!', '뀨트북 LG 그램! 최고!', 1);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '대훈이가 약해지만 약소훈!', '소들이 많으면? 소스!', 2);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '유중의 미! 웃음벨!', '포도가 자기 소개하면? 포도당!', 3);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '히피의 주인! 뀨잉!', '소가 부족하면? 산소 부족!', 4);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '쟁반으로 사랑을 탐하는 써니!', '만난지 5개월~!', 2);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '카피바라! 카피 보지마라!', '카피바라!', 2);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '미꾸라지! 미꾸미디엄!', '미꾸스몰!', 5);
INSERT INTO TBL_POST(ID, POST_TITLE, POST_CONTENT, USER_ID)
VALUES(SEQ_POST.NEXTVAL, '미국에 비가 오면!', 'USB', 2);

-- 댓글
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '하하하 너무 재밌어요!', 1, 6);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '히피가 너무 멋져요!', 2, 5);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '코카콜라 너무 맛있어요!!', 2, 4);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '번역을 너무 잘해요!!', 3, 3);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '유중이 너무 멋있어요!!', 3, 5);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '대훈이 몸짱이에요!!', 3, 7);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '철민이 똑똑해요~!', 4, 3);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '떡잎마을이 어디에요?', 4, 6);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '짱구는 몇살이에요?', 4, 6);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '유리는 멀쩡한가요?', 5, 1);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '수지는 첫사랑!', 5, 2);
INSERT INTO TBL_REPLY
VALUES(SEQ_REPLY.NEXTVAL, '서빙은 사랑을 타고~', 5, 3);



SELECT * FROM TBL_USER;
SELECT * FROM TBL_POST;
SELECT * FROM TBL_REPLY;


-- 떡잎마을에 살고 있는 사용자가 작성한 게시글
SELECT *
FROM TBL_POST
WHERE USER_ID IN (
	SELECT ID
	FROM TBL_USER
	WHERE USER_ADDRESS LIKE '%떡잎%'
);


SELECT ID
FROM TBL_USER
WHERE USER_ADDRESS LIKE '%떡잎%';


-- 카피바라가 들어간 게시글을 작성한 사람의 이름과 주소 조회
SELECT USER_EMAIL "이메일 주소" ,USER_ADDRESS "주소"
FROM TBL_USER
WHERE ID IN(
	SELECT USER_ID
	FROM TBL_POST 
	WHERE POST_TITLE LIKE '%카피바라%' OR POST_CONTENT LIKE '%카피바라%'
);

--SELECT USER_ID
--FROM TBL_POST tp 
--WHERE POST_TITLE LIKE '%카피바라%' OR POST_CONTENT LIKE '%카피바라%';


SELECT * FROM TBL_USER ;

-- 서울시에 살고 있는 사용자가 작성한 게시글에 달린 댓글의 총 개수

SELECT * FROM TBL_USER 
WHERE USER_ADDRESS LIKE '%서울%';


-- 서울에 살고 있는 사용자가 작성을 한 게시글
SELECT * FROM TBL_POST
WHERE USER_ID IN (
	SELECT ID FROM TBL_USER 
	WHERE USER_ADDRESS LIKE '%서울%'
);
 
-- 서울에 살고 있는 사용자가 작성을 한 게시글에 달린 댓글 모두
SELECT * FROM TBL_REPLY
WHERE POST_ID IN (
	SELECT ID FROM TBL_POST
	WHERE USER_ID IN (
		SELECT ID FROM TBL_USER 
		WHERE USER_ADDRESS LIKE '%서울%'
	)
);


SELECT COUNT(*) || '개' "서울 사용자가 작성한 게시글에 달린 댓글 수" FROM TBL_REPLY
WHERE POST_ID IN (
	SELECT ID FROM TBL_POST
	WHERE USER_ID IN (
		SELECT ID FROM TBL_USER 
		WHERE USER_ADDRESS LIKE '%서울%'
	)
);

SELECT * FROM TBL_REPLY;

-- 2번 게시글에 달린 댓글의 총 갯수
SELECT * FROM TBL_POST
WHERE ID = 2;

SELECT COUNT(*) || '개' "2번 게시글에 달린 댓글의 총 갯수" FROM TBL_REPLY
WHERE POST_ID = 2;


-- 게시글 내용에 미국이 들어간 사용자의 이메일
SELECT * FROM TBL_POST;

-- 1. 미국이 들어간 게시글 찾기
SELECT * FROM TBL_POST
WHERE POST_TITLE LIKE '%미국%' OR POST_CONTENT LIKE '%미국%';

-- 2. 미국이 들어간 게시글 작성 한 사용자 불러오기
SELECT * FROM TBL_USER
WHERE ID IN (
	SELECT USER_ID FROM TBL_POST
	WHERE POST_TITLE LIKE '%미국%' OR POST_CONTENT LIKE '%미국%'
);

--3. 이메일 최종적으로 불러오기
SELECT USER_EMAIL "게시글 내용에 미국이 들어간 사용자의 이메일" FROM TBL_USER
WHERE ID IN (
	SELECT USER_ID FROM TBL_POST
	WHERE POST_TITLE LIKE '%미국%' OR POST_CONTENT LIKE '%미국%'
);


--
-- 평균 댓글 개수보다 많이 달린 게시글
SELECT * FROM TBL_REPLY;


-- 댓글 테이블 에서 POST_ID 별로 댓글 수 집계
-- 게시판의 평균 댓글 수
SELECT AVG(COUNT(POST_ID)) FROM TBL_REPLY
GROUP BY POST_ID;

-- 게시판 별 댓글 수 집계
SELECT POST_ID, COUNT(POST_ID) FROM TBL_REPLY
GROUP BY POST_ID;

-- 평균 갯수 이상인거
SELECT POST_ID FROM TBL_REPLY
GROUP BY POST_ID
HAVING COUNT(POST_ID) > (
	SELECT AVG(COUNT(POST_ID)) FROM TBL_REPLY
	GROUP BY POST_ID
);

--댓글 평균 갯수가 이상인 게시글
SELECT * FROM TBL_POST
WHERE ID IN(
	SELECT POST_ID FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) > (
		SELECT AVG(COUNT(POST_ID)) FROM TBL_REPLY
		GROUP BY POST_ID
	)
);



-- 가장 댓글이 많이 달린 게시글을 작성한 사용자
SELECT POST_ID, COUNT(POST_ID) FROM TBL_REPLY
GROUP BY POST_ID;

SELECT TBP.POST_ID
FROM(
	SELECT POST_ID, COUNT(POST_ID) "REPLY_COUNT" FROM TBL_REPLY
	GROUP BY POST_ID
) TBP
WHERE REPLY_COUNT = (
	SELECT MAX(COUNT(POST_ID)) FROM TBL_REPLY
	GROUP BY POST_ID
);


SELECT USER_ID FROM TBL_POST
WHERE ID IN(
	SELECT TBP.POST_ID
	FROM(
		SELECT POST_ID, COUNT(POST_ID) "REPLY_COUNT" FROM TBL_REPLY
		GROUP BY POST_ID
	) TBP
	WHERE REPLY_COUNT = (
		SELECT MAX(COUNT(POST_ID)) FROM TBL_REPLY
		GROUP BY POST_ID
	)
);

SELECT * FROM TBL_USER
WHERE ID IN(
	SELECT USER_ID FROM TBL_POST
	WHERE ID IN(
		SELECT TBP.POST_ID
		FROM(
			SELECT POST_ID, COUNT(POST_ID) "REPLY_COUNT" FROM TBL_REPLY
			GROUP BY POST_ID
		) TBP
		WHERE REPLY_COUNT = (
			SELECT MAX(COUNT(POST_ID)) FROM TBL_REPLY
			GROUP BY POST_ID
		)
	)
);


-- 경기도에 거주하면서 댓글을 단 사용자 조회
-- 1. 경기도 거주하는 사용자
SELECT * FROM TBL_USER
WHERE USER_ADDRESS LIKE '%경기%';

-- 2. 경기도에 사는 사람이 작성한 댓글 조회
SELECT * FROM TBL_REPLY
WHERE USER_ID IN (
	SELECT ID FROM TBL_USER
	WHERE USER_ADDRESS LIKE '%경기%'
);

-- 3. 만약 작성된 댓글이 경기도에 사는 사람에 의한거라면 해당 경기도에 사는 사람을 조회
SELECT * FROM TBL_USER
WHERE ID IN(
	SELECT USER_ID FROM TBL_REPLY
	WHERE USER_ID IN (
		SELECT ID FROM TBL_USER
		WHERE USER_ADDRESS LIKE '%경기%'
	)
);


-- 댓글에 ?가 들어간 댓글을 작성한 사용자 조회
-- 1. ? 이 들어간 댓글을 먼저 찾기
SELECT * FROM TBL_REPLY
WHERE REPLY_CONTENT LIKE '%?%';

-- 유저 아이디 중복을 해결하기 위한 그룹바이 수행
SELECT USER_ID FROM TBL_REPLY
WHERE REPLY_CONTENT LIKE '%?%'
GROUP BY USER_ID;

-- 2. ? 이 들어간 댓글을 작성한 사용자의 정보를 가져오기
 SELECT * FROM TBL_USER
 WHERE ID IN(
	SELECT USER_ID FROM TBL_REPLY
	WHERE REPLY_CONTENT LIKE '%?%'
 );



--CASE 문
-- 값을 대체할 때 사용하는 문장
-- 조회를 할 때 값을 다른 값으로 대치하는거
-- SWITCH 
SELECT
	CASE USER_PASSWORD 
		WHEN '1234' THEN '일이삼사'
		WHEN '4567' THEN '사오육칠'
		ELSE '다른거'
	END
FROM TBL_USER;


SELECT 
	USER_EMAIL,
	CASE 
		WHEN USER_BIRTH >= TO_DATE('2000', 'YYYY') THEN '2000년대 생'
		WHEN USER_BIRTH < TO_DATE('2000', 'YYYY') THEN '1990년대 생'
	END "태어난 년도"
FROM TBL_USER;
	


SELECT *
FROM TBL_USER
WHERE USER_BIRTH >= TO_DATE('2000', 'YYYY');
	

-- 경기도인 서울인 구분하기
SELECT 
	USER_EMAIL "이메일",
	USER_ADDRESS "거주지",
	CASE 
		WHEN USER_ADDRESS LIKE '%서울%' THEN '서울인'
		WHEN USER_ADDRESS LIKE '%경기%' THEN '경기도인'
		ELSE '지방인'
	END "지역타입",
	USER_BIRTH "생일"
FROM TBL_USER;



-- 가장 댓글이 많이 달린 게시글을 작성한 사용자
-- 1. 댓글 확인
SELECT * FROM TBL_REPLY;

-- 2. 게시글 별로 댓글 모으기
SELECT POST_ID, (COUNT(POST_ID)) "REPLY_COUNT" FROM TBL_REPLY
GROUP BY POST_ID;

-- 3. 게시글 별 댓글 수 중에서 가장 큰 값을 찾기
SELECT MAX(COUNT(POST_ID)) FROM TBL_REPLY
GROUP BY POST_ID;

-- 4. 게시글 별 댓글 수 테이블 에서 댓글 수가 가장 최대 인거 뽑기
SELECT POST_ID FROM TBL_REPLY
GROUP BY POST_ID
HAVING COUNT(POST_ID) = (
	SELECT MAX(COUNT(POST_ID)) FROM TBL_REPLY
	GROUP BY POST_ID
);

-- 5. 댓글 수가 가장 많은 게시글 추출
SELECT * FROM TBL_POST
WHERE ID IN (
	SELECT POST_ID FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) = (
		SELECT MAX(COUNT(POST_ID)) FROM TBL_REPLY
		GROUP BY POST_ID
	)
);

-- 6. 해당 게시글 에서 유저의 아이디를 추출
SELECT USER_ID FROM TBL_POST
WHERE ID IN (
	SELECT POST_ID FROM TBL_REPLY
	GROUP BY POST_ID
	HAVING COUNT(POST_ID) = (
		SELECT MAX(COUNT(POST_ID)) FROM TBL_REPLY
		GROUP BY POST_ID
	)
);

-- 7. 위의 유저 아이디에 해당하는 유저 정보 가져오기
SELECT * FROM TBL_USER
WHERE ID IN (
	SELECT USER_ID FROM TBL_POST
	WHERE ID IN (
		SELECT POST_ID FROM TBL_REPLY
		GROUP BY POST_ID
		HAVING COUNT(POST_ID) = (
			SELECT MAX(COUNT(POST_ID)) FROM TBL_REPLY
			GROUP BY POST_ID
		)
	)
);

 








